### ISSUE TITLE
cudaDeviceReset

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_dev#150]
`cudaDeviceReset` is useful to flush data and clear up memory.

Ideally this would need to be in a destructor of the constant singleton, or similar, however order of destrcutors and the cuda context is not defined, so it is unsafe to issue any cuda calls in a destructor 

This will also invalidate CuRVE, so we need to think about this.

Also required for `cuda-memcheck`

**Comment by Robadob** [comment]
Can this not be placed inside `CUDAAgentModel` destructor? 
Simply, with an instance counter to only trigger when the final one is destroyed? (and an option to disable auto reset)

I'm assuming when the main method exits, the stack frame is popped and destructor on main scope objects is called before global/static scope stuff.

**Comment by ptheywood** [comment]
I'm still not super keen on using cuda calls in destructors, as you've pointed out, but If it did behave nicely that would probably be a good place for it. 

The alternative would be an explicit method to trigger it (`cuda_model->finalize()` or similar). 

For now, adding it to the destructor with a comment stating that it might cause issues in the destructor is probably reasonable, and if it causes issues we can make it explicit instead?

Might have an unintended side effect of increasing runtime of the test suite (i.e. the problem with using cmake's google test integration), although I don't think a deviceReset takes anywhere near as long as the first cuda context initialisation (200ms).

**Comment by Robadob** [comment]
If triggering reset in tests is undesirable, we can toggle it off with some global flag. We have a custom main for gtest, so enabling that would be easy.

**Comment by Robadob** [comment]
> I'm still not super keen on using cuda calls in destructors, as you've pointed out, but If it did behave nicely that would probably be a good place for it.

The main remaining issue we have is that we're using `gpuerrchk` inside destructors. Exceptions should not be thrown from destructors under any circumstance. (it leads to memory leaks?) This would be trivial to fix with a `gpuerrchk_noexcept` or similar (and then playing hunt to find all the cases requiring replacement), which just logs to console.

> Might have an unintended side effect of increasing runtime of the test suite (i.e. the problem with using cmake's google test integration), although I don't think a deviceReset takes anywhere near as long as the first cuda context initialisation (200ms).

Windows debug mode, with device reset each test, it was taking minimum 600ms per test that used `CUDAAgentModel`, rather than 40ms.

It (mostly) works for me on Windows, however it necessitates manually resetting all cudable members of `CUDAAgentModel` before the `cudaDeviceReset()`. Hence, with future updates and changes it could easily break (and not be noticed with it disabled during tests). Furthermore, we couldn't write an explicit test for this either, as it only fails if the offending cudable member has actually been used, and hence allocated some memory (such that `cudaFree` reports invalid argument), hence the test would need to be updated to catch new failure causes (which is unlikely to happen, without someone also fixing the destructor).
