### ISSUE TITLE
CMake: Address CMP0104

### ISSUE THREAD

**Issue by Robadob** [FLAMEGPU/FLAMEGPU2_dev#313]
Generating project with CMake 3.18.0+ causes this warning for all cuda targets:

```
CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.
  CUDA_ARCHITECTURES is empty for target "flamegpu2".
This warning is for project developers.  Use -Wno-dev to suppress it.
```

Presumably, renaming `CUDA_ARCH` to `CUDA_ARCHITECTURES` will fix it?

(This warning can be ignored, however the intention of policy warnings is that you fix behaviour as old behaviour is deprecated).

It can be suppressed with `set_policy(CMP0104 OLD)` at the top of `common.cmake`.

**Comment by ptheywood** [comment]
Using CUDA_ARCHITECTURES would tie us to 3.18+, won't allow us to test LTO until it supports it, and it's also very unclear what `-gencode`s it actually makes (and whether or not it adds furture arch JIT or not). 

I expect the `real_XX` maps to `compute_XX, sm_XX`, while `virtual_XX` maps to `comptue_XX,computeXX`, so compiling for 52,  and 61 with future support would be `real_52, real_61, virtual_61` but not 100% on this (+ I don't us requiring 3.18)

For now, at a glance the best option will be to set `CUDA_ARCHITECTURES` to `OFF`, rather than setting the policy to `old` which is labled as deprecated. 

This will also break all non-appveyor CI (which install latest avaialble) once it is released, so probably need to do this sooner rather than later.

**Comment by Robadob** [comment]
> This will also break all non-appveyor CI (which install latest avaialble) once it is released, so probably need to do this sooner rather than later.

It's not an error, it's a developer warning. It can be ignored. It just produces ALOT of spam, as it repeats that block from OP for every cuda target (of which there are many).

I'm happy to suppress it, can be popped in alongside the version check added for device link args. However, slightly worried it will be forgotten about (and hence may cause issues in future).
